# k8s/nova-backend-service.yaml

apiVersion: v1
kind: Service

metadata:
  name: nova-backend-service

spec:
  selector:
    app: nova-backend

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

  type: ClusterIP